# Known labels for each compound

CHEMICAL_LABELS = {
        'Acetaminophen': ['M2', 'M4', 'M5'],
        'Aflatoxin B1': ['M4'],
        'Carbon Tetrachloride': ['M4'],
        'Coumarin': ['M4'],
        'Cyclosporin A': ['M1', 'M5'],
        'Diclofenac': ['M2', 'M7'],
        'Doxorubicin': ['M5'],
        'Ethanol': ['M4'],
        'Isoniazid': ['M4'],
        'Phenobarbital': ['M4'],
        'Rotenone': ['M5'],
        'Tacrine': ['M5'],
        'Valproic Acid': ['M4', 'M5'],
        'adapin': [],
        'allopurinol': ['M4'],
        'allyl-alcohol': ['M2', 'M4'],
        'amiodarone': ['M5'],
        'aspirin': ['M1', 'M6'],
        'azathioprine': ['M2', 'M5'],
        'benzbromarone': ['M5'],
        'carbamazepine': ['M4'],
        'chlorpromazine': [],
        'cimetidine': [],
        'clofibrate': ['M1', 'M7'],
        'cyclophosphamide': ['M1', 'M2', 'M4', 'M5'],
        'diazepam': ['M6'],
        'ethionine': [],
        'fluphenazine': ['M1', 'M4'],
        'flutamide': ['M4', 'M5'],
        'gemfibrozil': ['M11'],
        'glibenclamide': ['M2'],
        'griseofulvin': ['M1', 'M6'],
        'haloperidol': ['M1', 'M4'],
        'hexachlorobenzene': ['M1', 'M4'],
        'bromobenzene': ['M5'],
        'hydroxyzine': [],
        'ibuprofen': ['M5', 'M6'],
        'imipramine': ['M1', 'M11'],
        'indomethacin': ['M1', 'M4'],
        'interleukin-1-beta,-human': ['M1'],
        'interleukin-6,-human': [],
        'ketoconazole': ['M1', 'M6'],
        'labetalol': [],
        'lomustine': ['M5', 'M6'],
        'methapyrilene': ['M1', 'M5'],
        'methyltestosterone': ['M8'],
        'naphthyl-isothiocyanate': ['M4', 'M5'],
        'nitrofurantoin': ['M4', 'M5'],
        'omeprazole': ['M4', 'M5'],
        'perhexiline': ['M5'],
        'phenylbutazone': ['M4', 'M5'],
        'phenytoin': ['M4'],
        'propylthiouracil': ['M4'],
        'rifampicin': ['M4', 'M11'],
        'sulfasalazine': ['M4'],
        'tetracycline': ['M5'],
        'thioacetamide': ['M4', 'M5'],
        'thioridazine': ['M1', 'M6', 'M7'],
        'transforming-growth-factor-beta-1': [],
        'WY-14643': ['M2', 'M5'],
        '2-acetamidofluorene': ['M6'],
        '2-Amino-3-methylimidazo-4-5-f-quinoline': [],
        '2-nitrofluorene': [],
        '4-Acetylaminofluorene-': [],
        '4--N-nitrosomethylamino--1--3-pyridyl-butan-1-one': ['M4'],
        'acetamide': [],
        'aflatoxin-B1': ['M4'],
        'benzo-a-pyrene': ['M4'],
        'benzoin': [],
        'benzyl-alcohol': ['M1'],
        'bis-2-ethylhexyl--phthalate': [],
        'clonidine': ['M1', 'M5'],
        'cyclophosphamide-hydrate': ['M1', 'M2', 'M4', 'M5'],
        'cyclosporin-A': ['M1', 'M5'],
        'diclofenac-sodium': ['M2', 'M7'],
        'D-mannitol': [],
        'ethanol': ['M4'],
        'fumonisin-B1': ['M1', 'M4', 'M7'],
        'Hydrazine-dihydrochloride-': [],
        'menthol': ['M5'],
        'methapyrilene-hydrochloride': ['M2', 'M5'],
        'nifedipine': [],
        'N-nitrosodimethylamine': ['M4'],
        'N-Nitrosomorpholine-': ['M5'],
        'phenobarbital-sodium': ['M4'],
        'phorbol-13-acetate-12-myristate': ['M8'],
        'piperonyl-butoxide': ['M4'],
        'pirinixic-acid': ['M2', 'M5'],
        'tolbutamide': ['M2'],
        'triclosan': ['M1', 'M8'],
        '1-Amino-2-4-dibromoanthra-quinone': [],
        '4-Acetylaminofluorene': [],
        'aristolochic-acid': ['M1', 'M2', 'M5', 'M7'],
        'bromodichloromethane': [],
        'chlorothalonil': ['M5'],
        'citrinin': ['M1', 'M7'],
        'Gallium-arsenide': ['M4'],
        'hydroquinone': ['M1', 'M4'],
        'lead-diacetate-trihydrate': ['M4', 'M7'],
        'monuron': [],
        'N-Ethyl-N--2-hydroxyethyl-nitrosamine': [],
        'N-Nitrosomorpholine': ['M5'],
        'ochratoxin-A': [],
        'potassium-bromate': ['M4'],
        'S--1-2-dichlorovinyl--L-cysteine': ['M5'],
        'streptozocin': ['M1', 'M5'],
        'Tris-2-3-dibromopropyl-phosphate': ['M4'],
        '2-3-7-8-tetrachlorodibenzodioxine': ['M4', 'M6'],
        'beclomethasone-dipropionate': [],
        'benzofuran': [],
        'bisphenol-A': ['M5'],
        'cadmium-dichloride': ['M4'],
        'cobalt-2---sulfate': ['M4'],
        'dibenz-a-h-anthracene': ['M6'],
        'dimethyl-sulfoxide': [],
        'ipratropium-bromide-hydrate': [],
        'N-methyl-N-nitrosurea': ['M2', 'M3'],
        'N-nitrosomorpholine': ['M5'],
        'phthalic-anhydride': [],
        'resorcinol': ['M5'],
        'sodium-dichromate': ['M4'],
        'sodium-metaarsenite': ['M4'],
        'styrene': ['M4'],
        'urea': [],
        'Amiodarone': ['M5'],
        'Cyclosporin-A': ['M1', 'M5'],
        'Diluted-Mainstream-Cigarette-Smoke-3R4F': ['M4'],
        'Diluted-Mainstream-Cigarette-Smoke-THS2-2': [],
        'total-particulate-matter--TPM--from-aerosol-THS2-2': [],
        'total-particulate-matter--TPM--from-mainstream-cigarette-smoke-3R4F': ['M4'],
        'nitrilotriacetic-acid': [],
        }
